/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 7a6ff3aec11486316cc9e82e7542c864)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	FREE_JOBS_QUEUE: Queue;
	ALLOWED_ORIGINS: "https://lmwares.com,https://www.lmwares.com,https://contratar.lmwares.com,https://lmwares-public.pages.dev" | "http://localhost:5273,http://127.0.0.1:5273,http://localhost:5274,http://127.0.0.1:5274,http://localhost:4273,http://127.0.0.1:4273,http://localhost:4274,http://127.0.0.1:4274";
	MEDIA_BASE_URL: "";
	PROJECT_SLUG: "lmwares" | "starter";
	FREE_SITE_BASE_DOMAIN: "lmwares.com";
	PUBLIC_WEB_URL: "https://contratar.lmwares.com" | "http://127.0.0.1:5273";
	PUBLIC_API_URL: "https://api.lmwares.com" | "http://127.0.0.1:8887";
	EMAIL_FROM: "notificaciones@lmwares.com";
	EMAIL_REPLY_TO: "soporte@lmwares.com";
	TURNSTILE_SECRET_KEY: string;
	TURNSTILE_DISABLED: string;
	FREE_RUNNER_TOKEN: string;
	GOOGLE_OAUTH_CLIENT_ID: string;
	GOOGLE_OAUTH_CLIENT_SECRET: string;
	MERCADO_PAGO_PUBLIC_KEY: string;
	MERCADO_PAGO_ACCESS_TOKEN: string;
	MERCADO_PAGO_TEST_MODE: string;
	MERCADO_PAGO_WEBHOOK_SECRET: string;
	MERCADO_PAGO_WEBHOOK_TEST_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface ProductionEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		EMAIL: SendEmail;
		FREE_JOBS_QUEUE: Queue;
		ALLOWED_ORIGINS: "https://lmwares.com,https://www.lmwares.com,https://contratar.lmwares.com,https://lmwares-public.pages.dev";
		MEDIA_BASE_URL: "";
		PROJECT_SLUG: "lmwares";
		FREE_SITE_BASE_DOMAIN: "lmwares.com";
		PUBLIC_WEB_URL: "https://contratar.lmwares.com";
		PUBLIC_API_URL: "https://api.lmwares.com";
		EMAIL_FROM: "notificaciones@lmwares.com";
		EMAIL_REPLY_TO: "soporte@lmwares.com";
		TURNSTILE_SECRET_KEY: string;
		TURNSTILE_DISABLED: string;
		FREE_RUNNER_TOKEN: string;
		GOOGLE_OAUTH_CLIENT_ID: string;
		GOOGLE_OAUTH_CLIENT_SECRET: string;
		MERCADO_PAGO_PUBLIC_KEY: string;
		MERCADO_PAGO_ACCESS_TOKEN: string;
		MERCADO_PAGO_TEST_MODE: string;
		MERCADO_PAGO_WEBHOOK_SECRET: string;
		MERCADO_PAGO_WEBHOOK_TEST_SECRET: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
