/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 597eb9f3246244074abc8d05c74f5ee5)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	FREE_JOBS_QUEUE: Queue;
	ALLOWED_ORIGINS: "https://lmwares.com,https://www.lmwares.com,https://contratar.lmwares.com,https://lmwares-public.pages.dev" | "http://localhost:5273,http://127.0.0.1:5273,http://localhost:5274,http://127.0.0.1:5274,http://localhost:4273,http://127.0.0.1:4273,http://localhost:4274,http://127.0.0.1:4274";
	DOMAIN_PROVIDER: "cloudflare-saas" | "manual";
	DOMAIN_REGISTRAR_PROVIDER: "porkbun" | "manual";
	CLOUDFLARE_ZONE_ID?: "fa8b7b1e5c20243be0e49ec794167eca";
	CLOUDFLARE_SAAS_CNAME_TARGET?: "customers.lmwares.com";
	MEDIA_BASE_URL: "";
	PROJECT_SLUG: "lmwares" | "starter";
	FREE_SITE_BASE_DOMAIN: "sitios.lmwares.com";
	PUBLIC_WEB_URL: "https://lmwares.com" | "http://127.0.0.1:5273";
	PUBLIC_API_URL: "https://api.lmwares.com" | "http://127.0.0.1:8887";
	MAP_SEARCH_BASE_URL: "https://nominatim.openstreetmap.org";
	MAP_SUGGEST_BASE_URL: "https://photon.komoot.io";
	EMAIL_FROM: "notificaciones@lmwares.com";
	EMAIL_REPLY_TO: "soporte@lmwares.com";
	MERCADO_PAGO_TECHNICAL_CHECKOUT_ENABLED?: "0";
	MERCADO_PAGO_COMMERCIAL_PAYMENTS_ENABLED?: "1";
	MERCADO_PAGO_COMMERCIAL_TEST_MODE?: "0";
	MERCADO_PAGO_MAINTENANCE_SUBSCRIPTIONS_ENABLED?: "1";
	MERCADO_PAGO_MAINTENANCE_TEST_MODE?: "0";
	ADMIN_ALERT_EMAIL?: "lmwareservice@gmail.com";
	TURNSTILE_SECRET_KEY: string;
	TURNSTILE_DISABLED: string;
	FREE_RUNNER_TOKEN: string;
	GOOGLE_OAUTH_CLIENT_ID: string;
	GOOGLE_OAUTH_CLIENT_SECRET: string;
	MERCADO_PAGO_PUBLIC_KEY: string;
	MERCADO_PAGO_ACCESS_TOKEN: string;
	MERCADO_PAGO_TEST_MODE: string;
	MERCADO_PAGO_WEBHOOK_SECRET: string;
	MERCADO_PAGO_WEBHOOK_TEST_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface ProductionEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		EMAIL: SendEmail;
		FREE_JOBS_QUEUE: Queue;
		ALLOWED_ORIGINS: "https://lmwares.com,https://www.lmwares.com,https://contratar.lmwares.com,https://lmwares-public.pages.dev";
		DOMAIN_PROVIDER: "cloudflare-saas";
		DOMAIN_REGISTRAR_PROVIDER: "porkbun";
		CLOUDFLARE_ZONE_ID: "fa8b7b1e5c20243be0e49ec794167eca";
		CLOUDFLARE_SAAS_CNAME_TARGET: "customers.lmwares.com";
		MEDIA_BASE_URL: "";
		PROJECT_SLUG: "lmwares";
		FREE_SITE_BASE_DOMAIN: "sitios.lmwares.com";
		PUBLIC_WEB_URL: "https://lmwares.com";
		PUBLIC_API_URL: "https://api.lmwares.com";
		MAP_SEARCH_BASE_URL: "https://nominatim.openstreetmap.org";
		MAP_SUGGEST_BASE_URL: "https://photon.komoot.io";
		EMAIL_FROM: "notificaciones@lmwares.com";
		EMAIL_REPLY_TO: "soporte@lmwares.com";
		MERCADO_PAGO_TECHNICAL_CHECKOUT_ENABLED: "0";
		MERCADO_PAGO_COMMERCIAL_PAYMENTS_ENABLED: "1";
		MERCADO_PAGO_COMMERCIAL_TEST_MODE: "0";
		MERCADO_PAGO_MAINTENANCE_SUBSCRIPTIONS_ENABLED: "1";
		MERCADO_PAGO_MAINTENANCE_TEST_MODE: "0";
		ADMIN_ALERT_EMAIL: "lmwareservice@gmail.com";
		TURNSTILE_SECRET_KEY: string;
		TURNSTILE_DISABLED: string;
		FREE_RUNNER_TOKEN: string;
		GOOGLE_OAUTH_CLIENT_ID: string;
		GOOGLE_OAUTH_CLIENT_SECRET: string;
		MERCADO_PAGO_PUBLIC_KEY: string;
		MERCADO_PAGO_ACCESS_TOKEN: string;
		MERCADO_PAGO_TEST_MODE: string;
		MERCADO_PAGO_WEBHOOK_SECRET: string;
		MERCADO_PAGO_WEBHOOK_TEST_SECRET: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
