/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 9251a8fa3f64c309a19b9a8a6fe63bbf)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	ALLOWED_ORIGINS: "http://localhost:5273,http://127.0.0.1:5273,http://localhost:5274,http://127.0.0.1:5274,http://localhost:4273,http://127.0.0.1:4273,http://localhost:4274,http://127.0.0.1:4274";
	MEDIA_BASE_URL: "";
	PROJECT_SLUG: "starter";
	FREE_SITE_BASE_DOMAIN: "lmwares.com";
	PUBLIC_WEB_URL: "http://127.0.0.1:5273";
	PUBLIC_API_URL: "http://127.0.0.1:8887";
	EMAIL_FROM: "notificaciones@lmwares.com";
	EMAIL_REPLY_TO: "soporte@lmwares.com";
	TURNSTILE_SECRET_KEY: string;
	TURNSTILE_DISABLED: string;
	FREE_RUNNER_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
