/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: bedf3096ca304d4d3f6d391a20fa0b77)
interface __BaseEnv_Env {
	FREE_RUNNER_QUEUE: Queue;
	IMAGES: ImagesBinding;
	PUBLIC_API_URL: "https://api.lmwares.com";
	PUBLIC_API: Fetcher /* starter-public-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_API_URL">> {}
}
